"""empty message

Revision ID: 361bd39e3843
Revises: 95f437a18b52
Create Date: 2022-06-16 10:46:31.682932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361bd39e3843'
down_revision = '95f437a18b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['user_id'])
    op.drop_column('user', 'image_file')
    op.alter_column('user_type', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_type', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
